name: Sync Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    name: Sync
    if: "github.repository_owner == 'materialred'"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: upstream
          fetch-depth: 0
          token: ${{ secrets.PUBLISH_PAT || secrets.GITHUB_TOKEN }}

      - name: Fetch and merge upstream
        run: |
          git 
          git remote add upstream https://github.com/mollyim/mollyim-android.git
          git fetch main
          git merge --ff-only upstream/main

      - name: Push changes
        run: |
          git push origin dev
          git tag | grep -xP 'v\d+(?:\.\d+){2,3}' | xargs -r git push origin
